# Generated by Django 4.0.4 on 2022-06-05 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 17, 8, 40, 693250))),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('level_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('minimum_point', models.IntegerField()),
            ],
            options={
                'db_table': 'membership_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPromotion',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('require_level', models.IntegerField(blank=True, default=0)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'db_table': 'sales_promotion',
                'managed': False,
            },
        ),
    ]
