# Generated by Django 4.0.4 on 2022-06-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['ee_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeleShift',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start', models.TimeField()),
                ('till', models.TimeField()),
            ],
            options={
                'db_table': 'tele_shift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusStaff',
            fields=[
                ('bs_id', models.OneToOneField(db_column='ee_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bs_child', serialize=False, to='employees.employee')),
                ('vaccine', models.IntegerField()),
            ],
            options={
                'db_table': 'bus_staff',
                'managed': False,
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dv_id', models.OneToOneField(db_column='ee_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dv_child', serialize=False, to='employees.employee')),
                ('license_id', models.CharField(max_length=20)),
                ('exp_year', models.IntegerField()),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('mn_id', models.OneToOneField(db_column='ee_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mn_child', serialize=False, to='employees.employee')),
                ('certificate_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='TelephoneStaff',
            fields=[
                ('ts_id', models.OneToOneField(db_column='ee_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ts_child', serialize=False, to='employees.employee')),
            ],
            options={
                'db_table': 'telephone_staff',
                'managed': False,
            },
            bases=('employees.employee',),
        ),
    ]
