# Generated by Django 4.0.4 on 2022-06-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bustype', models.TextField(blank=True, choices=[('NORMAL', 'Normal'), ('LIMO', 'Limousine'), ('VIP', 'Vip')], default=None, null=True)),
                ('total_seat', models.IntegerField()),
                ('maxload', models.IntegerField()),
                ('sleeper_type', models.TextField(blank=True, choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('CABIN', 'Cabin')], default=None, null=True)),
            ],
            options={
                'db_table': 'bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_point', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('distance', models.IntegerField(blank=True, default=None, null=True)),
                ('total_time', models.TimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stop_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('empty_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripSchedule',
            fields=[
                ('sched_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luggage_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.TextField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, default=None, null=True)),
                ('bustype', models.TextField(blank=True, choices=[('NORMAL', 'Normal'), ('LIMO', 'Limousine'), ('VIP', 'Vip')], default=None, null=True)),
            ],
            options={
                'db_table': 'trip_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripStaff',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trip_staff',
                'managed': False,
            },
        ),
    ]
